### ISSUE TITLE
Mood Indicator Un-highlights upon clicking another field

### ISSUE THREAD

**Issue by madelines-code** [MRKnutson/Vocal_dpl_w21#111]
When you are entering your journal entry details after you have stopped recording, the smiley face un-highlights after I click another field on the form.

1. click record button
2. click stop recording
3. start entering info into the modal box and click a mood face
4. click the next field and the mood face is no longer highlighted

![Unhighlighted](https://user-images.githubusercontent.com/25010754/151600173-c665cc30-f6cf-4849-9855-03daf68ce16c.png)
)

I expected the smiley face to stay highlighted so it makes me think I have to click it again to make sure it got the data.

**Comment by MRKnutson** [comment]
Resolved
