### ISSUE TITLE
Profile Photo Use Suggestion

### ISSUE THREAD

**Issue by madelines-code** [MRKnutson/Vocal_dpl_w21#112]
There is an option to add a profile photo but the profile photo is not used anywhere. It would be nice if it showed up in the circle in the top right corner. This is probably something you already have in the works..
![Screen Shot 2022-01-28 at 11 20 08 AM](https://user-images.githubusercontent.com/25010754/151600665-22edc6a4-c834-42bd-a978-0f83d51385ab.png)
.

**Comment by jleosco** [comment]
It would also be nice if the email or a username showed in the corner instead of "user"

**Comment by rubyreed** [comment]
added to navbar
