### ISSUE TITLE
Nice to have

### ISSUE THREAD

**Issue by Vitamin-Ccc** [MRKnutson/Vocal_dpl_w21#113]
# Suggestion
This is not a bug but could be a nice feature to add. Once I created an account/login, it brings me to the recording page, but I was a bit confused on what to do next. Maybe changing the play button to a record button would make more sense, or add "Start recording". And it would be nice to have some instructions at the top of the page on how this app works, what can the user expect once they click on the button.

**Comment by jimibue** [comment]
I agree with this, and also the play button needs to be a recording button, that is a bug.

**Comment by rubyreed** [comment]
will add! when will gives us finished instructions
