### ISSUE TITLE
Uploading a very large image

### ISSUE THREAD

**Issue by XavioArts** [MRKnutson/Vocal_dpl_w21#116]
Summary of Bug/Issue- The button sits uploading forever when uploading a very large image. Some sort of error handling to let the user know the image is too large would solve this. 

Steps to reproduce- go to /recordings. click on view details on a recording. click add image, add a large file

<img width="982" alt="imageUploadCrash" src="https://user-images.githubusercontent.com/68799139/151603149-ae1a2670-5f8e-49ed-a7ba-362e71e183e6.png">

**Comment by XavioArts** [comment]
Eventually got a 422 in the console but it took a very long time

**Comment by rubyreed** [comment]
might add alert for size
