### ISSUE TITLE
Empty string tags

### ISSUE THREAD

**Issue by jleosco** [MRKnutson/Vocal_dpl_w21#117]
Adding a new tag that is and empty input will save the tag with the name "Object, Object"

Record > add new tag as an empty string/empty input box > timeline > recording details > edit recording > tag field contains a tag " [ object Object]"

<img width="830" alt="Screen Shot 2022-01-28 at 11 37 58 AM" src="https://user-images.githubusercontent.com/94190517/151603419-0a2c3208-79a1-4b8a-a95f-c403e65fe6df.png">

**Comment by DennyPlank** [comment]
closed, thanks for point this out
