### ISSUE TITLE
hitting 'enter' while creating recording details destroys recording

### ISSUE THREAD

**Issue by jimibue** [MRKnutson/Vocal_dpl_w21#118]
#Summary
After making a recording and while adding details if you hit enter while in the title section or tag section the modal form goes away and recording is list.  

steps to reproduce
1. create a recording
2. in modal form hit enter while in title input or tags input
3. modal/recording goes away

# expected (in my opionion) 
1. hitting enter in the while in title input should create the recording to the DB
2. hitting enter in the tag section should create the tag but not submit the recording form
---or---
3. hitting enter should not cause the form/recording to be destroyed (just ignore if enter is hit)

**Comment by rubyreed** [comment]
fixed by asher
