### ISSUE TITLE
Activity Map Hover Shows No Data

### ISSUE THREAD

**Issue by madelines-code** [MRKnutson/Vocal_dpl_w21#123]
When you are on the activity page and you hover over a highlighted spot on the annual activity map, the box that pops up shows no data. 

1. click activity page
2. hover over a colored box

![Screen Shot 2022-01-28 at 12 01 36 PM](https://user-images.githubusercontent.com/25010754/151605945-e94ba747-4d8c-45a5-bd29-dada73e01db4.png)

expected some useful data

got no info

**Comment by rubyreed** [comment]
fixed! 
isInteractive = {false}
