### ISSUE TITLE
Multiple saves of same recording

### ISSUE THREAD

**Issue by jleosco** [MRKnutson/Vocal_dpl_w21#124]
Clicked save multiple times on the save recording page saves that recording multiple times.

Begin recording > enter recording title, ect... > click save multiple times > timeline

<img width="898" alt="Screen Shot 2022-01-28 at 12 03 15 PM" src="https://user-images.githubusercontent.com/94190517/151606229-44067069-9c69-4813-bf14-4948480e04ba.png">

<img width="1603" alt="Screen Shot 2022-01-28 at 12 00 58 PM" src="https://user-images.githubusercontent.com/94190517/151606240-ba1054fd-c974-453e-a5b4-7ac011654245.png">

Expected:
Save button is disabled after clicking once or clicking multiple time only saves one copy of the recording

**Comment by MRKnutson** [comment]
This is resolved.
