### ISSUE TITLE
Mood page formatting and purpose

### ISSUE THREAD

**Issue by madelines-code** [MRKnutson/Vocal_dpl_w21#125]
The mood page graph extends past the right hand window so as a user I wonder if data is not being shown since I don't see the end of the box. The mood page also seems redundant since you can see a map of your moods on the activity page. 
![Screen Shot 2022-01-28 at 12 03 53 PM](https://user-images.githubusercontent.com/25010754/151606371-61220a26-7b32-4756-9fce-e4d3e8ac00c2.png)

expecting: end of graph to show

got: graph looks cut off (it's not but the box surrounding it is)

**Comment by rubyreed** [comment]
donezo
