### ISSUE TITLE
Daily log displays differently if you add photo

### ISSUE THREAD

**Issue by madelines-code** [MRKnutson/Vocal_dpl_w21#127]
On the Activity page under Daily Log, if you click a post that has no photo the text is formatted differently than if you click a post that you have added photos to. It also only displays the first photo you added, not all of them. A button to click the post you select would be helpful so you can see the details through that area. 
![Screen Shot 2022-01-28 at 12 17 41 PM](https://user-images.githubusercontent.com/25010754/151608285-eeb1ac4c-ba2c-40ab-86fc-342002e9ec16.png)
![Screen Shot 2022-01-28 at 12 17 52 PM](https://user-images.githubusercontent.com/25010754/151608289-2b34f38d-9b54-40e6-822e-34f9c523c361.png)

**Comment by rubyreed** [comment]
mike fixed this
