### ISSUE TITLE
long title

### ISSUE THREAD

**Issue by Vitamin-Ccc** [MRKnutson/Vocal_dpl_w21#128]
# Summary
Super long title of the recording will go past the modal and also the box.

# Screenshot
<img width="1427" alt="Screen Shot 2022-01-28 at 12 18 42 PM" src="https://user-images.githubusercontent.com/75514586/151608095-9fe2b65e-a6b4-4a80-9093-47fb786b4758.png">

<img width="975" alt="Screen Shot 2022-01-28 at 12 06 10 PM" src="https://user-images.githubusercontent.com/75514586/151608212-46f704a6-5931-4b97-8a21-0048bf07100d.png">

**Comment by DennyPlank** [comment]
Thanks for letting us know! fixed.
