### ISSUE TITLE
Timeline(My Journal Entry) glitch

### ISSUE THREAD

**Issue by StinChoi** [MRKnutson/Vocal_dpl_w21#129]
# Summary of Bug/Issue(required)
- Bug noticed in Timeline (My Journal Entries)
- When trying to edit my recording and adding a tag
- Tag entry entered but while I am trying to select the added tag, page freezes

# Steps to reproduce(required)
- Timeline to My Journal Entries
- View details to Edit Recording
- Under Mood levels, click the “+” to add in a tag
- Entry of a tag you want, hitting the check mark to display it to “Select Tag”
- Select tag option and the page freeze

# screenshot(if needed)
![Uploading Screen Shot 2022-01-28 at 12.26.07 PM.png…]()

# expected result (if needed)

# actual result (if needed)

**Comment by MRKnutson** [comment]
This was already fixed by related issue of being able to add empty string as tag
